# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

platform :ios, "9.0"
use_frameworks!


def pods_base

    pod 'Caishen'
    pod 'CardIO'
    pod 'Material', '~> 2.0'
    pod 'SwiftyJSON'
    pod 'Alamofire'
    pod 'SwiftSpinner'
    pod 'GoogleMaps'
    pod 'GooglePlaces'
    pod 'Google/Analytics'
    pod 'Google/SignIn'
    pod 'Socket.IO-Client-Swift'
    pod 'NVActivityIndicatorView'
    pod 'UrbanAirship-iOS-SDK', '7.2.2'
    pod 'youtube-ios-player-helper', '~> 0.1.4'
    pod 'FBSDKCoreKit'
    pod 'DatePickerDialog'
    pod 'ZDCChat'

end

target 'GorilasApp' do
    pods_base
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end

